---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oncall-heartbeat
  namespace: monitoring
spec:
  encryptedData:
    url: AgAG4b+OA7WE2c8Pzg1sz0UNsbH1PRICD0T8v/3CWYIhxvm4imTqTDUPOuFLMbnjPZDUs8dTGJ4+S2d8JnTGmKitZJ6AuFlRDUfnIinHhCIeT9bVTiHwQvnkXHYYb7IUQlxGRoEkpcWoN/XoUlpnmBrMdDv0kYn2JQvDHgfg4SIiORbjWRSCH8Rn05B1caEU6Vkga5QHan3k+1u3298Ua2fOOXNRWYz49bWODN8mehrMgx3n/v9nh/R02WGf6DSYXipQ74MjEBty0kEZ5xscVdyXmqxLwcuXX1n7Yw4gASNHZQEvSlTg3+hb9NVydcjSkTmRNQNECEzhJt41fVRZ8pyv5AEM5gR3rtL8xQAr/KnUSDFuKYnEXZLqPCMw+4x3p/10W4sDY8FuDlS40xNC4FEbvedz19SQY72ePxricR9UTherANknxrGE5VHsgS+WjlXU0MJxzCpcIPIW5tQq9Uze9uKWySv9bcrJFsNBiZzOu/giFI6Fb+opWFTD6vMDuwubk98K9DtgGjeZzVzooAfXWThT4Vpn0MAUKvoUsHiDSaDrfryB6I/W3+wTDqNP69Ne+leqwv1eHziMMakRgz8OhzIf29/INFumzS1w8sTQdb7wrQe5N2O+rzmwAk6Xy1dp+x44xKdUdUq+BgqUsaWqQMqoXsDFfQtjUQOHc+o3WonWjWgCnVZ6oDKM6Z8Mn27UQmYjtvA7DnjVrrKc+HB0eMF0HkWhKqzPIGHB96c1PPcoP88lwBxw/9zjJpbeT62xUC+UKQ7dBHzXmWw2lbb1cHr223lcf8YYenS63K24Rtm6jKwsAMxxS5MKcspxqi5Edu9jyu2QRKvvH79t
  template:
    metadata:
      name: oncall-heartbeat
      namespace: monitoring
    type: Opaque
