apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/xxczaki/homelab
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
      exclude: "{**/resources/**}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-cd
  ignoreDifferences:
    - group: ""
      kind: Service
      namespace: wicek
      name: raspberrypi
      jsonPointers:
        - /spec/externalName
    - group: ""
      kind: Service
      namespace: wicek
      name: homeassistant
      jsonPointers:
        - /spec/externalName
  syncPolicy:
    automated:
      selfHeal: true
