apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw-operator
  namespace: openclaw-system
spec:
  project: default
  source:
    chart: openclaw-operator
    repoURL: ghcr.io/openclaw-rocks/charts
    targetRevision: 0.16.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openclaw-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
