---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wicek-ha-ssh-key
  namespace: wicek
spec:
  encryptedData:
    id_ed25519: AgC1Jf98lTTN61XuefqCia/Ih1ow7hCNrkR4AQ28i7sGC8wV8xTPak4IsS+IJUfU0faG8le/HHtmxX1ObwfMUddytxxt42ysaUvxbm1ixXGHzNWopu8LJCsiZhvjykAbhN+oriX4gVbAEx02Mh4s/p0FJJJVZCyomofJscN/HUW43CpyvDEGXaxzJJjDHLpqDM+9pcXPBNtG8GslX7kC5ungP3szzbNTO0e2Y/7KgtX2k3rrw0ivbZCUW1Wt3fytovjd3DQfUCG+9URjGy13oWDinMESLGtI+BME5fZEbKKvgqItXZueYCumJ1pmPcOOiFs3QPOT0OTzKaXfVm6A++NDRmFE2vNV97BgmWYq4/eIPuVlQmA9T4dzSCwE3ujjWqp/muM4gAzxUGAhI3ci0CtTYzoyJlxlpr/vEwGkrrwv7mTU9uXnnoTFBgaqVK2jtr48Jp+e+rpHLilIHH9IIf8oyoRy+H7VgH3noSkh5fLT+ioFKODurWCvNMvG6n2C43qb6v9xKfyn8vV8m3HP3mL/h1F/6VaiNs+totF8yBQuAJ+4n6Y16pHxpo0L1uMhfdzr7WdgcNEClpq1rQC9QQo8Buz+XIYqflJLxUwQSyfO6XQJ58Q64aVBq+BGI97yP9ygTRTuKgJJWVsawxHm3JDs5EfzNDyl4ZoiDpafT+VpwMRzJez29zA1MPsaVfUgZyNzQJ8Wl/EFteMAEs0mIt6eAzqjGx7gsb6UmbMamp79er/wIwgl/WdoIKVkCUXF9a5wgUHbBTz70sFFoapT0iJzhsHnVKVyJnHB9x56XrzLwQ8IBaJE+QD5JRXBym2gr3KaonQOHZHQCAir3Y0+nzG99YFuIsZRs5kcS+11qlQ3uQUaAo+qA9ne81Nd2rz6l3kSk9pGtb0yoN8GeMibBVI+r2Zb1MrzPv+kwJundbHHKe3vyO1GNCbQe1ViudgE1AAtTDje4bXBvXM9Pl+hD5PXjmP3nrdvDDMTalPt6P9xGNP8iX8TIsiwQrl07t93QWIIrdkhMRW8fvL5/LT1oPaEf5EB6DY8ItnM7FFJFIPBtOtSw0h4QbVqh3wl0MROkrccUV1UYU+33EwaoOS8pvVfaQeLxaTri/dHrfRs/M+pNoXjBb6urNmhNtfEEEnVXBoRsBHDF+K/oHFt2M+TsjvaF0q9DFxF/jTGsSXFXLSZOZMIdLZzTuUCTYZ8nCE5Hfgez/TcxcJfhBRHqggCHD/da0B7gP4S2Yu/LFUF6bjQsJS1VA==
  template:
    metadata:
      name: wicek-ha-ssh-key
      namespace: wicek
    type: Opaque
