apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: wicek
  annotations:
    tailscale.com/tailnet-fqdn: homeassistant.tail12a84.ts.net.
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 22
      protocol: TCP
      name: ssh
