# Synced from the 1Password "Wicek" vault by the 1Password Operator.
# Mounted only into the broker sidecar (see broker.secrets in chart.yaml).
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-cloud
  namespace: wicek
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  itemPath: vaults/4to3l755ao33le6mi4fm5prirq/items/osaneiwlqhjzx2jw2ycaclmcym
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: home-assistant
  namespace: wicek
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  itemPath: vaults/4to3l755ao33le6mi4fm5prirq/items/ca3xgqtfiyujwd5q2jflyozufe
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: unifi
  namespace: wicek
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  itemPath: vaults/4to3l755ao33le6mi4fm5prirq/items/rcwua5weuwyzpqfw736ks4b3vu
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: home-assistant-ssh
  namespace: wicek
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  itemPath: vaults/4to3l755ao33le6mi4fm5prirq/items/mhzegk6vlnjbsd7blg35ivqlea
