apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: monitoring
spec:
  project: default
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.0.1
    helm:
      valuesObject:
        cluster:
          name: "homelab"

        global:
          scrapeInterval: 120s

        destinations:
          Metrics:
            type: prometheus
            url: https://prometheus-prod-39-prod-eu-north-0.grafana.net/api/prom/push
            secret:
              create: false
            auth:
              type: basic
          Logs:
            type: loki
            url: https://logs-prod-025.grafana.net/loki/api/v1/push
            secret:
              create: false
            auth:
              type: basic
          Traces:
            type: otlp
            url: https://tempo-prod-18-prod-eu-north-0.grafana.net:443
            protocol: grpc
            secret:
              create: false
            auth:
              type: basic
            metrics:
              enabled: false
            logs:
              enabled: false
            traces:
              enabled: true

        clusterMetrics:
          enabled: true
          collector: alloy-metrics
          kube-state-metrics:
            namespacesDenylist:
              - monitoring
              - kube-system
              - longhorn-system
          cadvisor:
            metricsTuning:
              dropEmptyContainerLabels: true
              dropEmptyImageLabels: true
              excludeNamespaces:
                - monitoring
                - kube-system
                - longhorn-system
        prometheusOperatorObjects:
          enabled: true
          collector: alloy-singleton
        clusterEvents:
          enabled: true
          collector: alloy-singleton
          excludeNamespaces:
            - monitoring
            - kube-system
            - longhorn-system
        nodeLogs:
          enabled: true
          collector: alloy-logs
        podLogsViaLoki:
          enabled: true
          collector: alloy-logs
          excludeNamespaces:
            - monitoring
            - kube-system
            - longhorn-system
        hostMetrics:
          enabled: true
          collector: alloy-metrics
          linuxHosts:
            enabled: true
            metricsTuning:
              includeMetrics:
                - node_hwmon_temp_celsius
        integrations:
          alloy:
            instances:
              - name: alloy
                labelSelectors:
                  app.kubernetes.io/name:
                    - alloy-metrics
                    - alloy-singleton
                    - alloy-logs

        telemetryServices:
          kube-state-metrics:
            deploy: true
          node-exporter:
            deploy: true

        collectors:
          alloy-metrics:
            presets:
              - clustered
              - statefulset
            alloy:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  memory: 512Mi
          alloy-singleton:
            presets:
              - singleton
            extraConfig: |
              mimir.rules.kubernetes "rules" {
                address = "https://prometheus-prod-39-prod-eu-north-0.grafana.net"

                basic_auth {
                  username = nonsensitive(remote.kubernetes.secret.metrics.data["username"])
                  password = remote.kubernetes.secret.metrics.data["password"]
                }
              }
            alloy:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  memory: 512Mi
          alloy-logs:
            presets:
              - filesystem-log-reader
              - daemonset
            alloy:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  memory: 512Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - ServerSideApply=true