---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw-ha-ssh-key
  namespace: openclaw-system
spec:
  encryptedData:
    id_ed25519: AgCSNLwksDoZScP0zs3FH9ABobJP7TYxeULHuswo/RDMgmwYz6Eg96h7pnHg/FSKIefDkP48BbpctoLBkgvKmFTcEk1z/j0cQzfhkNpH2c0LSdXvIgJbk59fN65q9UlGF3MtKTLScpATRzBKXmryDHNATfMy1UDBE+MCa3CHc7pQcYKf6iJ/WmHz6HZX5oOaxDsIfYsnjpNrSpOwNJGCnGoAR+NCI82JkZEOuAbjaaLsvFp9VRmlANccEFGDsdc4e2TcIMBqaEL8fr7m9kiB73OcAo0qI5FrLQYeVvZQMeE5xgEXbDEuP/t9LR+O25wGOuKwCBUr4zEiM5mTrc3KLM3+1wEEF0WBTKAtPI/dMaZ+4o0nIhwmNDEm6yIgCG3fA+JK6TQYpVluejXa/ZFpLwRtq9somlieYhSECuxoal1UPRyZ5RkaoH8Wq6zql4JqX6TfTQYzkG8cR5CD3RfHGuS99jqcq0oqTLcJsdYwxNI2lgodd2lUp5lsWQ1woT2Kdb2jOkSKE+bIAB6DdL3mY8g76N58e2Mhj/r7qDEbw3LCCIE6Ju2iKNj4fdTlxoZ7dxlr6QhIc9qKGwlagxV++IlSYlIYWk+sOFRpFXw8b+p9NfqVjr+ggPUfHDIF9AejZw8V9+KUAKx0OlgSUeeZx9gLBDbolfthxzf8VMBWha7pSOlOi/Wv/ULWvMCdH6PoH24mDiZPRbezE5iEEoxJHiLWkcaswF9COXE5etDeRdErUwzJzcnNKm9zHqXhilM3E3nKkRW0smD0zJv8Dt9zWhpGlgot2fyirIkefoKYNzSjxl8KWvDj8wPGwyak59symaU2G7V/rrq3PuMX+dXCm/FyLq2HPu8+MLtwG8ogyC4nNXw5m+PM0hpKpiATGGczAy0QhNMBMCflESVrWCBNQnqpgeW4Q144QqlGQElsB08rmd50k4b8JIv+7aQHtLp7l1ipH0M5Rg3UEol+81kMv09Sa4Xyfl9zdFQfZqJs5MBf5zaEJYXatYFCLeJhoYGqlT+q49SUyWsXJZ48eEH9SHNPtp15vhmmetDbWsnFk563qCdPjYZqsU7nc4Kl1Sp8y7hetlgOZIhKEv2cVlXhgZqIyZeloxLu1s29+GIch/ElsXk5Kj28Ika+5NvKX7kRgHIYWNlrniRpYAQnoqaKTW3jSsS0XhUhRHQ2r0+SpXm7xz3JQtUB6gpOjpN06Kx37GAvE1rjTTV4OYS1MQcW6CxlDkM1JT4LiMz2/gcw1w3vClRsjQ==
  template:
    metadata:
      creationTimestamp: null
      name: openclaw-ha-ssh-key
      namespace: openclaw-system
    type: Opaque
