#!/usr/bin/env bash
set -euo pipefail

# Generates the applications table in readme.md from the apps/ directory.
# The table is placed between AUTO-GENERATED:apps-table:START/END markers.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
README="$REPO_ROOT/readme.md"
APPS_DIR="$REPO_ROOT/apps"

START_MARKER="<!-- AUTO-GENERATED:apps-table:START -->"
END_MARKER="<!-- AUTO-GENERATED:apps-table:END -->"

get_type() {
	local app_dir="$1"
	if grep -q 'chart:' "$app_dir/application.yaml" 2>/dev/null; then
		echo "Helm"
	elif [ -f "$app_dir/resources/kustomization.yaml" ]; then
		echo "Git + Kustomize"
	else
		echo "Git"
	fi
}

get_version() {
	local app_dir="$1"

	# Try targetRevision from application.yaml
	local ver
	ver="$(grep 'targetRevision:' "$app_dir/application.yaml" 2>/dev/null | head -1 | awk '{print $2}')"

	# If it's a branch ref, try kustomization.yaml or other yamls in the directory
	if [ "$ver" = "HEAD" ] || [ "$ver" = "main" ]; then
		ver=""
		# Check kustomization.yaml for ref=
		if [ -f "$app_dir/resources/kustomization.yaml" ]; then
			ver="$(grep -o 'ref=v[^"]*' "$app_dir/resources/kustomization.yaml" 2>/dev/null | head -1 | sed 's/ref=//')"
		fi
		# Check sibling yamls for a chart targetRevision
		if [ -z "$ver" ]; then
			ver="$(grep 'targetRevision:' "$app_dir"/*.yaml 2>/dev/null | grep -v 'HEAD\|main' | head -1 | awk '{print $NF}')"
		fi
	fi

	echo "${ver:--}"
}

# Build the table into a temp file
TABLE_FILE="$(mktemp)"
trap 'rm -f "$TABLE_FILE"' EXIT

{
	echo "$START_MARKER"
	echo "<!-- This table is auto-generated by scripts/generate-apps-table.sh — do not edit manually -->"
	echo "| Application | Type | Version |"
	echo "|---|---|---|"

	for app_dir in "$APPS_DIR"/*/; do
		[ -f "$app_dir/application.yaml" ] || continue
		app="$(basename "$app_dir")"
		type="$(get_type "$app_dir")"
		ver="$(get_version "$app_dir")"
		echo "| [$app](apps/$app) | $type | $ver |"
	done

	echo "$END_MARKER"
} > "$TABLE_FILE"

# Replace the section between markers in the README
if ! grep -q "$START_MARKER" "$README"; then
	echo "Error: start marker not found in $README" >&2
	exit 1
fi

awk -v start="$START_MARKER" -v end="$END_MARKER" -v table_file="$TABLE_FILE" '
	$0 == start {
		while ((getline line < table_file) > 0) print line
		close(table_file)
		skip=1
		next
	}
	$0 == end { skip=0; next }
	!skip { print }
' "$README" > "$README.tmp" && mv "$README.tmp" "$README"

echo "Updated applications table in readme.md"
